#!/bin/bash
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

SCRIPT_NAME=`realpath $0`
FGLUNZIPDIR=`dirname $SCRIPT_NAME` 
#echo "FGLUNZIPDIR=$FGLUNZIPDIR"
export FGL_LENGTH_SEMANTICS=BYTE
export LC_ALL="en_US.UTF-8"
pushd "`pwd`" >/dev/null
cd "$FGLUNZIPDIR"
#recompile only when needed
source "$FGLUNZIPDIR/myfglcomp.sh"
GIT_LONG_VERSION=`git describe --tags --long --abbrev=8`
myfglcomp checkgit && fglrun checkgit "$GIT_LONG_VERSION"
fglcomp -M -r -Wall fglunzip
myfglcomp mygetopt
popd > /dev/null
export FGLUNZIPDIR
#exec fglrun -p $FGLUNZIPDIR/fgljp.42m "$@"
exec fglrun "$FGLUNZIPDIR/fglunzip.42m" "$@"
